name: brew test-bot

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-bot:
    strategy:
      matrix:
        include:
          - os: macos-14
            arch: arm64
          - os: macos-14
            arch: x86_64
    runs-on: ${{ matrix.os }}
    env:
      HOMEBREW_ARCH: ${{ matrix.arch }}
    steps:
      - name: Set up Rosetta 2 (for x86_64 cross-compilation)
        if: matrix.arch == 'x86_64'
        run: sudo softwareupdate --install-rosetta --agree-to-license

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ matrix.os }}-${{ matrix.arch }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ matrix.os }}-${{ matrix.arch }}-rubygems-

      - name: Run cleanup (x86_64)
        if: matrix.arch == 'x86_64'
        run: arch -x86_64 brew test-bot --only-cleanup-before

      - name: Run cleanup (arm64)
        if: matrix.arch == 'arm64'
        run: brew test-bot --only-cleanup-before

      - name: Run setup (x86_64)
        if: matrix.arch == 'x86_64'
        run: arch -x86_64 brew test-bot --only-setup

      - name: Run setup (arm64)
        if: matrix.arch == 'arm64'
        run: brew test-bot --only-setup

      # - run: brew test-bot --only-tap-syntax

      # - run: brew test-bot --only-formulae
      #   if: github.event_name == 'pull_request'

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: bottles_${{ matrix.os }}_${{ matrix.arch }}
          path: '*.bottle.*'
